version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: meu_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_local

volumes:
  postgres_data:

networks:
  rede_local:
    driver: bridge
